export enum SoilType {
    RED_OXISOL           = 'RED_OXISOL',
    RED_YELLOW_OXISOL    = 'RED_YELLOW_OXISOL',
    YELLOW_OXISOL        = 'YELLOW_OXISOL',
    RED_ULTISOL          = 'RED_ULTISOL',
    RED_YELLOW_ULTISOL   = 'RED_YELLOW_ULTISOL',
    RED_ALFISOL          = 'RED_ALFISOL',
    QUARTZARENIC_ENTISOL = 'QUARTZARENIC_ENTISOL',
    LITHOLIC_ENTISOL     = 'LITHOLIC_ENTISOL',
    FLUVIC_ENTISOL       = 'FLUVIC_ENTISOL',
    MOLLISOL             = 'MOLLISOL',
    HISTOSOL             = 'HISTOSOL',
    PLANOSOL             = 'PLANOSOL',
    GLEYSOL              = 'GLEYSOL',
    INCEPTISOL           = 'INCEPTISOL',
    VERTISOL             = 'VERTISOL',
    PLINTHOSOL           = 'PLINTHOSOL',
    SANDY_SOIL           = 'SANDY_SOIL',
    CLAY_SOIL            = 'CLAY_SOIL',
    SILTY_SOIL           = 'SILTY_SOIL',
    AMAZONIAN_DARK_EARTH = 'AMAZONIAN_DARK_EARTH',
    UNIDENTIFIED         = 'UNIDENTIFIED',
};
  
export const SoilTypeDesc: Record<SoilType, string> = {
    [SoilType.RED_OXISOL]:           'Latossolo Vermelho',
    [SoilType.RED_YELLOW_OXISOL]:    'Latossolo Vermelho-Amarelo',
    [SoilType.YELLOW_OXISOL]:        'Latossolo Amarelo',
    [SoilType.RED_ULTISOL]:          'Argissolo Vermelho',
    [SoilType.RED_YELLOW_ULTISOL]:   'Argissolo Vermelho-Amarelo',
    [SoilType.RED_ALFISOL]:          'Nitossolo Vermelho (Terra Roxa)',
    [SoilType.QUARTZARENIC_ENTISOL]: 'Neossolo Quartzarênico',
    [SoilType.LITHOLIC_ENTISOL]:     'Neossolo Litólico',
    [SoilType.FLUVIC_ENTISOL]:       'Neossolo Flúvico',
    [SoilType.MOLLISOL]:             'Chernossolo',
    [SoilType.HISTOSOL]:             'Organossolo',
    [SoilType.PLANOSOL]:             'Planossolo',
    [SoilType.GLEYSOL]:              'Gleissolo',
    [SoilType.INCEPTISOL]:           'Cambissolo',
    [SoilType.VERTISOL]:             'Vertissolo',
    [SoilType.PLINTHOSOL]:           'Plintossolo',
    [SoilType.SANDY_SOIL]:           'Solo Arenoso',
    [SoilType.CLAY_SOIL]:            'Solo Argiloso',
    [SoilType.SILTY_SOIL]:           'Solo Siltoso',
    [SoilType.AMAZONIAN_DARK_EARTH]: 'Terra Preta de Índio (TPI)',
    [SoilType.UNIDENTIFIED]:         'Não Identificado',
};