import {
    faSeedling,
    faArrowRight,
    faTriangleExclamation,
    faCloud,
    faCloudSun,
    faWind,
    faDroplet,
    faGaugeHigh,
    faPlus,
    faTractor,
    faFileText,
    faUpload,
    faChartLine,
    faTemperatureHalf,
    faSun,
    faLocationDot,
    faMap,
    faArrowTrendUp,
    faArrowTrendDown,
    faMinus,
    faWheatAwn,
    faDrumstickBite,
    faMugHot,
    faLeaf,
    faNeuter,
    faHome,
    faChartBar,
    faCube
} from '@fortawesome/free-solid-svg-icons'

export const ICONS_DASHBOARD = {
    SEEDLING : faSeedling,
    ARROW_RIGHT : faArrowRight,
    TRIANGLE_EXCLAMATION : faTriangleExclamation,
    CLOUD : faCloud,
    CLOUD_SUN : faCloudSun,
    GAUGE_HIGH : faGaugeHigh,
    WIND : faWind,
    DROPLET : faDroplet,
    PLUS : faPlus,
    TRACTOR : faTractor,
    FILE_TEXT : faFileText,
    UPLOAD : faUpload, 
    CHART_LINE : faChartLine,
    TEMPERATURE_HALF : faTemperatureHalf,
    SUN : faSun,
    LOCATION_DOT : faLocationDot,
    MAP : faMap,
    NEUTER: faNeuter,
    ARROW_TREND_UP : faArrowTrendUp,
    ARROW_TREND_DOWN : faArrowTrendDown,
    MINUS : faMinus,
    WHEAT_AWN : faWheatAwn,
    DRUMSTICK_BITE : faDrumstickBite,
    MUG_HOT : faMugHot,
    LEAF : faLeaf,
    HOME : faHome,
    CHART_BAR : faChartBar,
    CUBE : faCube
}