import {
    faArrowLeft,
    faChartLine,
    faSeedling,
    faTractor,
    faMugHot,
    faWheatAwn,
    faArrowTrendUp,
    faArrowTrendDown,
    faMinus,
    faBoxes,
    faCube,
    faBell,
    faFileLines,
    faCheck,
    faCircleDot,
    faDrumstickBite,
    faCow,
    faCubes,
    faSearch,
    faCalendar,
    faChartPie,
    faGaugeHigh,
    faFile,
    faArrowsRotate
} from '@fortawesome/free-solid-svg-icons';
import { faCottonBureau } from '@fortawesome/free-brands-svg-icons';

export const ICONS_MARKET = {
    ARROW_LEFT: faArrowLeft,
    CHART_LINE: faChartLine,
    SEEDLING: faSeedling,
    TRACTOR: faTractor,
    MUG_HOT: faMugHot,
    WHEAT_AWN: faWheatAwn,
    ARROW_TREND_UP: faArrowTrendUp,
    ARROW_TREND_DOWN: faArrowTrendDown,
    MINUS: faMinus,
    BOXES: faBoxes,
    CUBE: faCube,
    BELL: faBell,
    FILE_LINES: faFileLines,
    CHECK: faCheck,
    CIRCLE_DOT: faCircleDot,
    DRUMSTICK_BITE: faDrumstickBite,
    COW: faCow,
    COTTON_BUREAU: faCottonBureau,
    CUBES: faCubes,
    WHEAT_WHEAT: faWheatAwn,
    SEARCH: faSearch,
    CALENDAR: faCalendar,
    CHART_PIE: faChartPie,
    GAUGE_HIGH: faGaugeHigh,
    FILE: faFile,
    ARROWS_ROTATE: faArrowsRotate
}