import { 
    faUsers,
    faHandHoldingDollar,
    faTree,
    faScaleBalanced,
    faLeaf,
    faBuildingWheat,
    faShieldHalved,
    faBasketShopping,
    faChalkboardUser,
    faBrain,
    faBolt,
    faInfoCircle,
    faBriefcase,
    faNewspaper,
    faHandshake,
    faComputer,
    faRocket,
    faCode,
    faMap,
    faChartLine,
    faCircleQuestion,
    faBook,
    faEnvelope,
    faFileContract,
    faServer,
    faShield,
    faLock,
    faCheckCircle,
    faPaperPlane,
    faTriangleExclamation,
    faFlag,
    faDatabase
} from '@fortawesome/free-solid-svg-icons';
import { 
    faLinkedin,
    faTelegram,
    faYoutube,
    faInstagram
} from '@fortawesome/free-brands-svg-icons';

export const ICONS_FOOTER = {
    DATABASE : faDatabase,
    USERS : faUsers,
    HANDHOLDINGDOLLAR : faHandHoldingDollar,
    TREE : faTree,
    SCALEBALANCED : faScaleBalanced,
    LEAF : faLeaf,
    BUILDINGWHEAT : faBuildingWheat,
    SHIELDHALVED : faShieldHalved,
    BASKETSHOOPING : faBasketShopping,
    CHALKBOARDUSER : faChalkboardUser,
    BRAIN : faBrain,
    BOLT : faBolt,
    INFOCIRCLE : faInfoCircle,
    BRIEFCASE : faBriefcase,
    COMPUTER : faComputer,
    NEWSPAPER : faNewspaper,
    FILECONTRACT : faFileContract,
    FLAG : faFlag,
    HANDSHAKE : faHandshake,
    ROCKET : faRocket,
    CODE : faCode,
    MAP : faMap,
    CHARTLINE : faChartLine,
    CIRCLEQUESTION : faCircleQuestion,
    BOOK : faBook,
    ENVELOPE : faEnvelope,
    SERVER : faServer,
    SHIELD : faShield,
    LOCK : faLock,
    CHECKCIRCLE : faCheckCircle,
    PAPERPLANE : faPaperPlane,
    TRIANGLEEXCLAMATION : faTriangleExclamation,
    LINKEDIN : faLinkedin,
    TELEGRAM : faTelegram,
    YOUTUBE : faYoutube,
    INSTAGRAM : faInstagram
};
