import {
    faEye,
    faHandshake,
    faTrash,
    faClock,
    faXmark,
    faSpinner,
    faCalendar,
    faFileContract,
    faPen,
    faCircleXmark,
    faCheck,
    faList,
    faPlus,
    faTag,
    faPencil,
    faTriangleExclamation,
    faWheatAlt,
    faChevronDown,
    faArrowUp,
    faArrowDown,
    faBoxesStacked
} from '@fortawesome/free-solid-svg-icons';

export const ICONS_BARTER = {
    EYE: faEye,
    HANDSHAKE: faHandshake,
    TRASH: faTrash,
    CLOCK: faClock,
    XMARK: faXmark,
    SPINNER: faSpinner,
    CALENDAR: faCalendar,
    FILE_CONTRACT: faFileContract,
    PEN: faPen,
    CIRCLE_XMARK: faCircleXmark,
    CHECK: faCheck,
    LIST: faList,
    PLUS: faPlus,
    TAG: faTag,
    PENCIL: faPencil,
    TRIANGLE_EXCLAMATION: faTriangleExclamation,
    WHEAT: faWheatAlt,
    CHEVRON_DOWN: faChevronDown,
    ARROW_UP: faArrowUp,
    ARROW_DOWN: faArrowDown,
    BOXES_STACKED: faBoxesStacked
}
